stages:
  train_linear:
    cmd: python linear_reg_learn.py
    deps:
    - linear_reg_learn.py
    - prepare/X_train.csv
    - prepare/y_train.csv
    outs:
    - models/linear_model.pkl
    metrics:
    - results/linear/metrics_learn.json:
        cache: false
  validate_linear:
    cmd: python linear_reg_valid.py
    deps:
    - linear_reg_valid.py
    - models/linear_model.pkl
    - prepare/X_val.csv
    - prepare/y_val.csv
    metrics:
    - results/linear/metrics_valid.json:
        cache: false
  fullrun_linear:
    cmd: python linear_reg_full.py
    deps:
    - prepare/X_full.csv
    - prepare/y_full.csv
    - models/linear_model.pkl
    - linear_reg_full.py
    metrics:
    - results/linear/metrics_full.json



  train_tree:
    cmd: python tree_learn.py
    deps:
    - prepare/X_train.csv
    - prepare/y_train.csv
    - tree_learn.py
    outs:
    - models/tree_model.pkl
    - results/tree/tree_structure.png
    metrics:
    - results/tree/metrics_learn.json:
        cache: false
  validate_tree:
    cmd: python tree_valid.py
    deps:
    - models/tree_model.pkl
    - prepare/X_val.csv
    - prepare/y_val.csv
    - tree_valid.py
    outs:
    - results/tree/actual_vs_pred_valid.png
    - results/tree/residual_plot_valid.png
    metrics:
    - results/tree/metrics_valid.json:
        cache: false
  fullrun_tree:
    cmd: python tree_full.py
    deps:
    - models/tree_model.pkl
    - prepare/X_full.csv
    - prepare/y_full.csv
    - tree_full.py
    outs:
    - results/tree/actual_vs_pred_full.png
    - results/tree/residual_plot_full.png
    metrics:
    - results/tree/metrics_full.json:
        cache: false
  train_cat:
    cmd: python catboost_learn.py
    deps:
    - catboost_learn.py
    - prepare/X_train.csv
    - prepare/y_train.csv
    outs:
    - models/catboost_model.cbm
    - results/catboost/feature_importance.csv
    - results/catboost/feature_importance.png
    metrics:
    - results/catboost/metrics_learn.json:
        cache: false
  validate_cat:
    cmd: python catboost_valid.py
    deps:
    - catboost_valid.py
    - models/catboost_model.cbm
    - prepare/X_val.csv
    - prepare/y_val.csv
    outs:
    - results/catboost/actual_vs_pred_valid.png
    - results/catboost/residual_plot_valid.png
    metrics:
    - results/catboost/metrics_valid.json:
        cache: false
  fullrun_cat:
    cmd: python catboost_full.py
    deps:
    - catboost_full.py
    - models/catboost_model.cbm
    - prepare/X_full.csv
    - prepare/y_full.csv
    outs:
    - results/catboost/actual_vs_pred_full.png
    - results/catboost/residual_plot_full.png
    metrics:
    - results/catboost/metrics_full.json:
        cache: false
  train_xgb:
    cmd: python xgboost_learn.py
    deps:
    - prepare/X_train.csv
    - prepare/y_train.csv
    - xgboost_learn.py
    outs:
    - models/xgboost_model.json
    - results/xgboost/feature_importance.csv
    - results/xgboost/feature_importance.png
    metrics:
    - results/xgboost/metrics_learn.json:
        cache: false
  validate_xgb:
    cmd: python xgboost_valid.py
    deps:
    - models/xgboost_model.json
    - prepare/X_val.csv
    - prepare/y_val.csv
    - xgboost_valid.py
    outs:
    - results/xgboost/actual_vs_pred_valid.png
    - results/xgboost/residual_plot_valid.png
    metrics:
    - results/xgboost/metrics_valid.json:
        cache: false
  fullrun_xgb:
    cmd: python xgboost_full.py
    deps:
    - models/xgboost_model.json
    - prepare/X_full.csv
    - prepare/y_full.csv
    - xgboost_full.py
    outs:
    - results/xgboost/actual_vs_pred_full.png
    - results/xgboost/residual_plot_full.png
    metrics:
    - results/xgboost/metrics_full.json:
        cache: false
  train_mlp:
    cmd: python mlp_learn.py
    deps:
    - mlp_learn.py
    - prepare/X_train.csv
    - prepare/y_train.csv
    outs:
    - models/mlp_model.pkl
    - results/mlp/loss_curve.png
    - results/mlp/weights_histogram_layer1.png
    - results/mlp/weights_histogram_layer2.png
    - runs/mlp/
    metrics:
    - results/mlp/metrics_learn.json:
        cache: false
  validate_mlp:
    cmd: python mlp_valid.py
    deps:
    - mlp_valid.py
    - models/mlp_model.pkl
    - prepare/X_val.csv
    - prepare/y_val.csv
    outs:
    - results/mlp/actual_vs_pred_valid.png
    - results/mlp/residual_plot_valid.png
    metrics:
    - results/mlp/metrics_valid.json:
        cache: false
  fullrun_mlp:
    cmd: python mlp_full.py
    deps:
    - mlp_full.py
    - models/mlp_model.pkl
    - prepare/X_full.csv
    - prepare/y_full.csv
    outs:
    - results/mlp/actual_vs_pred_full.png
    - results/mlp/residual_plot_full.png
    metrics:
    - results/mlp/metrics_full.json:
        cache: false
