mlp:
  hidden_layer_sizes:
  - 100
  - 50
  activation: relu
  solver: adam
  max_iter: 1000
  random_state: 42
  alpha: 0.001  # 可尝试 0.001、0.01、0.0001

tree:
  max_depth: 8
  random_state: 42

catboost:
  depth: 8
  iterations: 200
  learning_rate: 0.1
  random_state: 42

xgb:
  max_depth: 6
  n_estimators: 100
  learning_rate: 0.1
  random_state: 42

linear:
  normalize: false
